version: "1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "9098:9098"
    volumes:
      - .:/home/app/code
      - /home/app/code/node_modules
